services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    profiles: ["dynamodb"]
    ports:
      - "8000:8000"

  cassandra:
    image: cassandra:latest
    profiles: ["cassandra"]
    ports:
      - "9042:9042"

  redis:
    image: redis:alpine
    profiles: ["redis"]
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    profiles: ["mongodb"]
    ports:
      - "27017:27017"

  firestore:
    image: mtlynch/firestore-emulator:latest
    profiles: ["firestore"]
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16-alpine
    profiles: ["postgres"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
