services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    profiles: ["dynamodb"]
    ports:
      - "8000:8000"

  cassandra:
    image: cassandra:latest
    profiles: ["cassandra"]
    ports:
      - "9042:9042"
