services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    profiles: ["dynamodb"]
    ports:
      - "8000:8000"

  cassandra:
    image: cassandra:latest
    profiles: ["cassandra"]
    ports:
      - "9042:9042"

  redis:
    image: redis:alpine
    profiles: ["redis"]
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    profiles: ["mongodb"]
    ports:
      - "27017:27017"
